### ISSUE TITLE
Ch.10 Output doesn't match requirments

### ISSUE THREAD

**Issue by eidosam** [Aya-Alabrash/HYF-JavaScript#1]
In challenge 10 https://github.com/Aya-Alabrash/HYF-JavaScript/blob/dc375dff219d45090d2476031ef72740e83e8b52/week%203%20edited/script.js#L105
The output doesn't match the desired requirements, It shows

> Amazing Joe's Garage, we service motorbikecaravans, bikes, buses and car.

And in the next run:

> Amazing Joe's Garage, we service motorbikecaravans, bikes, buses, cars, scooters and boat. 

As you can see the first and last are not pluralized! can you please fix it.

**Comment by Aya-Alabrash** [comment]
i'll see it &fix it

**Comment by Aya-Alabrash** [comment]
it's done 
in for loop i was started from 1 so the first element at index 0 will not be fixed with the addition

**Comment by eidosam** [comment]
👍
