### ISSUE TITLE
Ch.10 Redundant code

### ISSUE THREAD

**Issue by eidosam** [Aya-Alabrash/HYF-JavaScript#2]
In https://github.com/Aya-Alabrash/HYF-JavaScript/blob/dc375dff219d45090d2476031ef72740e83e8b52/week%203%20edited/script.js#L115
isn't `vehiclesList[vehiclesList.length - 2]` covered in the loop?

**Comment by Aya-Alabrash** [comment]
because i want the item before last to joining by only 'es ' without ',' after es or 's'

**Comment by eidosam** [comment]
👍
