### ISSUE TITLE
Ch.13 Array is not object literal

### ISSUE THREAD

**Issue by eidosam** [Aya-Alabrash/HYF-JavaScript#3]
You are asked to create an object (literal) https://github.com/Aya-Alabrash/HYF-JavaScript/blob/dc375dff219d45090d2476031ef72740e83e8b52/week%203%20edited/script.js#L138

**Comment by Aya-Alabrash** [comment]
ok i'll fix it

**Comment by Aya-Alabrash** [comment]
i fix it 👍

**Comment by eidosam** [comment]
👍
